[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_YOUTUBE_API_KEY = "AIzaSyDNCuHT7Bw7VO5AtWWzqrogsumX4Uvxej4"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200